spring:

  datasource:
    username: delivery-demo
    password: password
    url: jdbc:postgresql://postgresql:5432/items-process

  kafka:
    bootstrap-servers: kafka:9092

service:
  applications-storage:
    host: http://localhost/applications-storage

  items-controller:
    host: http://items-controller:8080/
