spring:

  datasource:
    username: delivery-demo
    password: password
    url: jdbc:postgresql://localhost:5433/items-process

  kafka:
    bootstrap-servers: localhost:9092

service:
  applications-storage:
    host: http://localhost/applications-storage

  items-controller:
    host: http://localhost/items-controller
