spring:

  datasource:
    username: delivery-demo
    password: password
    url: jdbc:postgresql://postgresql:5432/items-process

  kafka:
    bootstrap-servers: kafka:9092

service:
  applications-storage:
    host: http://applications-storage:8080

  items-controller:
    host: http://items-controller:8080
