version: '3.5'

services:

  excamad:
    image: kotovdenis/excamad:latest
    ports:
      - "8090:8080"

  postgresql:
    image: 'postgres:16-alpine'
    container_name: postgresql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=delivery-demo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=public
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  applications-storage:
    container_name: applications-storage
    build:
      context: .././applications-storage
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
      - kafka

  items-controller:
    container_name: items-controller
    build:
      context: .././items-controller
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8082:8080"
    depends_on:
      - postgresql
      - kafka

  items-keeper:
    container_name: items-keeper
    build:
      context: .././items-keeper
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8083:8080"
    depends_on:
      - postgresql
      - kafka

  items-process:
    container_name: items-process
    build:
      context: .././items-process
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8084:8080"
    depends_on:
      - postgresql
      - kafka

  notification-center:
    container_name: notification-center
    build:
      context: .././notification-center
    environment:
      - SPRING_PROFILES_ACTIVE
      - TELEGRAM_API_KEY
    ports:
      - "8085:8080"
    depends_on:
      - postgresql
      - kafka

  operator-back:
    container_name: operator-back
    build:
      context: .././operator-back
    environment:
      - SPRING_PROFILES_ACTIVE
    ports:
      - "8086:8080"
    depends_on:
      - postgresql
      - kafka


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - applications-storage
      - items-controller
      - items-keeper
      - items-process
      - operator-back

volumes:
  postgres-data:
    name: postgres-data