version: '3.5'

services:

  postgresql:
    image: 'postgres:16-alpine'
    container_name: postgresql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=delivery-demo
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=delivery-demo
    restart: always
    networks:
      - backend

volumes:
  postgres-data:
    name: postgres-data

networks:
  backend: { }