spring:
    datasource:
      username: delivery-demo
      password: password
      url: jdbc:postgresql://localhost:5433/operator-back

    kafka:
      bootstrap-servers: localhost:9092

service:
  items-keeper:
    host: http://localhost/items-keeper/

  applications-storage:
    host: http://localhost/applications-storage/