spring:
  application:
    name: operator-back

  jpa:
    database: postgresql

  liquibase:
    change-log: migrations/master.xml

  kafka:
    topics:
      task-status-updated: operator.task-status-updated-events