spring:
    datasource:
      username: delivery-demo
      password: password
      url: jdbc:postgresql://postgresql:5432/operator-back

    kafka:
      bootstrap-servers: kafka:9092

service:
  items-keeper:
    host: http://localhost/items-keeper

  applications-storage:
    host: http://localhost/applications-storage