spring:
    datasource:
      username: delivery-demo
      password: password
      url: jdbc:postgresql://postgresql:5432/operator-back

    kafka:
      bootstrap-servers: kafka:9092

service:
  items-keeper:
    host: http://items-keeper:8080

  applications-storage:
    host: http://applications-storage:8080