spring:
  application:
    name: applications-storage

  jpa:
    database: postgresql

  liquibase:
    change-log: migrations/master.xml

  kafka:
    topics:
      start-processing: process.start-processing


service:
  telegram:
    enabled: true
    api-key: ${TELEGRAM_API_KEY}