spring:
    datasource:
      username: delivery-demo
      password: password
      url: jdbc:postgresql://postgresql:5432/applications-storage

    kafka:
      bootstrap-servers: kafka:9092

service:
  telegram:
    host: https://chatter.salebot.pro/api