spring:
  application:
    name: items-keeper
  datasource:
    username: delivery-demo
    password: admin
    url: jdbc:postgresql://localhost:5433/delivery-demo

  jpa:
    database: postgresql

  liquibase:
    change-log: migrations/master.xml