spring:
    datasource:
      username: delivery-demo
      password: password
      url: jdbc:postgresql://postgresql:5432/items-keeper

service:
  items-controller:
    host: http://items-controller:8080
