spring:
  application:
    name: items-controller

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: migrations/master.xml