style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 5
  MaxLineLength:
    active: false
  ThrowsCount:
    active: false
  UnusedPrivateMember:
    active: false
  UseCheckOrError:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  UseRequire:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  MayBeConst:
    active: false
formatting:
  MaximumLineLength:
    active: false
  ArgumentListWrapping:
    active: false
  MultiLineIfElse:
    active: false
empty-blocks:
  EmptyDefaultConstructor:
    active: false
  EmptyFunctionBlock:
    active: false
complexity:
  LongParameterList:
    constructorThreshold: 9
    functionThreshold: 8
  NestedBlockDepth:
    active: false
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  ComplexCondition:
    active: false
  TooManyFunctions:
    active: false
performance:
  SpreadOperator:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
  SwallowedException:
    active: false
potential-bugs:
  ImplicitDefaultLocale:
    active: false
