name: Build application

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build